version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myusertest
      POSTGRES_PASSWORD: mypasswordtest
      POSTGRES_DB: mydb_test
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
